name: ci

on:
  push:
    branches:
      - 'main'
  schedule:
    # Build monthly
    - cron: '0 0 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ vars.DOCKERHUB_RW_USER }}
    strategy:
      fail-fast: false
      matrix:
        variant:
          - 0-ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.event.repository.name }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_RW_USER }}
          password: ${{ secrets.DOCKERHUB_RW_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ vars.DOCKERHUB_RW_USER }}/${{ github.event.repository.name }}:${{ matrix.variant }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v4.0.0
        with:
          username: ${{ vars.DOCKERHUB_RW_USER }}
          password: ${{ secrets.DOCKERHUB_RW_TOKEN }}
          repository: ${{ vars.DOCKERHUB_RW_USER }}/${{ github.event.repository.name }}
          short-description: ${{ github.event.repository.description }}
      - uses: gautamkrishnar/keepalive-workflow@v2
